### ISSUE TITLE
执行demo.bpm报错

### ISSUE THREAD

**Issue by Guodongchang** [alibaba/compileflow#26]
Caused by: java.lang.IllegalAccessException: Class com.alibaba.compileflow.engine.common.utils.ClassUtils can not access a member of class java.lang.Math with modifiers "private"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.Class.newInstance(Class.java:436)
	at com.alibaba.compileflow.engine.common.utils.ClassUtils.newInstance(ClassUtils.java:39)
	at com.alibaba.compileflow.engine.common.utils.ClassUtils.newInstance(ClassUtils.java:27)
	at com.alibaba.compileflow.engine.common.utils.ObjectFactory.lambda$getInstance$0(ObjectFactory.java:34)
	... 94 more

**Comment by xuan698400** [comment]
这个错误应该是无法运行Math的privite方法吧。有demo.bpm可以发下。原则上要指定的节点action，方法最好还是public的。不支持privite。
