### ISSUE TITLE
服务器上能正常执行，但在yarn环境下报错。

### ISSUE THREAD

**Issue by iamhungry** [alibaba/compileflow#32]
[INFO] 2021-09-11 14:30:15.142  - [taskAppId=TASK-13-70-92]:[217] - process has exited, execute path:/tmp/dolphinscheduler/exec/process/1/13/70/92, processId:31343 ,exitStatusCode:0
[INFO] 2021-09-11 14:30:15.267  - [taskAppId=TASK-13-70-92]:[129] -  -> com.alibaba.compileflow.engine.common.CompileFlowException: compile file[/tmp/.flowclasses/compileflow/stateless/bmp/DemoFlow.java] to class[compileflow.stateless.bmp.DemoFlow] failed,Pb(387) Only a type can be imported. ls.xchange.data.task.demo.DatasourceJob resolves to a package
	Pb(387) Only a type can be imported. ls.xchange.data.task.demo.StringJob resolves to a package
	Pb(2) DatasourceJob cannot be resolved to a type
	Pb(2) StringJob cannot be resolved to a type
	Pb(2) DatasourceJob cannot be resolved to a type
	
		at com.alibaba.compileflow.engine.process.preruntime.compiler.impl.support.EcJavaCompiler.compile(EcJavaCompiler.java:233)
		at com.alibaba.compileflow.engine.process.preruntime.compiler.impl.CompilerImpl.compileJavaCode(CompilerImpl.java:52)
		at com.alibaba.compileflow.engine.runtime.impl.AbstractProcessRuntime.compileJavaCode(AbstractProcessRuntime.java:251)
		at com.alibaba.compileflow.engine.runtime.impl.AbstractProcessRuntime.lambda$compile$0(AbstractProcessRuntime.java:131)
		at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
		at com.alibaba.compileflow.engine.runtime.impl.AbstractProcessRuntime.compile(AbstractProcessRuntime.java:131)
		at com.alibaba.compileflow.engine.process.impl.AbstractProcessEngine.getCompiledRuntime(AbstractProcessEngine.java:79)
		at com.alibaba.compileflow.engine.process.impl.AbstractProcessEngine.lambda$getProcessRuntime$1(AbstractProcessEngine.java:73)
		at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
		at com.alibaba.compileflow.engine.process.impl.AbstractProcessEngine.getProcessRuntime(AbstractProcessEngine.java:72)
		at com.alibaba.compileflow.engine.process.impl.TbbpmStatelessProcessEngineImpl.execute(TbbpmStatelessProcessEngineImpl.java:37)
		at ls.xchange.data.task.demo.Task.main(Task.java:26)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
		at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:851)
		at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
		at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
		at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
		at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:926)
		at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:935)
		at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
	21/09/11 14:30:15 INFO util.ShutdownHookManager: Shutdown hook called
	21/09/11 14:30:15 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-69fc985a-8ea5-4315-b5dd-1c8b027e538e

**Comment by iamhungry** [comment]
java源码生成的路径换了个目录，能正常生成，但编译报错。
