### ISSUE TITLE
运行有异常

### ISSUE THREAD

**Issue by lianlianyi** [alibaba/compileflow#5]
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1226)
	at com.alibaba.compileflow.engine.runtime.impl.AbstractStatelessProcessRuntime.buildFollowingNodes(AbstractStatelessProcessRuntime.java:94)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)

**Comment by yusu1210** [comment]
已修复
