### ISSUE TITLE
Wanted: who's using compileflow/您在使用compileflow吗？

### ISSUE THREAD

**Issue by xuan698400** [alibaba/compileflow#9]

**Comment by xuan698400** [comment]
First of all, thanks sincerely for constantly using and supporting Compileflow. We will try our best to keep Compileflow better, and keep growing Compileflow community. To attract more people to use and contribute to Compileflow, please comment in this issue to include the following information:

Your company, school or organization.
Your city and country.
Your contact info: blog, email, twitter (at least one).
For what scenario do you use Compileflow
You can refer to the following sample answer for the format:

Company: Alibaba
Location: Hangzhou, China
Contact: @xuan698400 (Twitter)
Purpose: trouble-shoot production issues
首先诚挚地感谢每一位持续关注并使用 Compileflow 的朋友。我们会持续投入，力图把 Compileflow 变得更好，把 Compileflow 社区变得更加繁荣。为了更好的聆听社区的声音，吸引更多的人使用和参与，我们期待您在此提交一条评论, 评论内容包括:

您所在公司、学校或组织
您所在的城市、国家
您的联系方式: 微博、邮箱、微信 (至少一个)
您将 Compileflow 用于哪些业务场景
您可以参考下面的样例来提供您的信息：

公司：阿里巴巴
网址：https://www.alibabagroup.com/ （方便用获取LOGO）
地点：中国杭州
联系方式：xuan.xa@alibaba-inc.com
场景：交易下单
再次感谢你的参与!!!

**Comment by shuanger051** [comment]
这个插件，在2019版本的皮肤会变形。

**Comment by sunhuo** [comment]
com.alibaba.compileflow.engine.common.CompileFlowException: java.lang.NullPointerException
	at com.alibaba.compileflow.engine.process.preruntime.converter.impl.parser.support.AbstractFlowStreamParser.parse(AbstractFlowStreamParser.java:79)
	at com.alibaba.compileflow.engine.process.preruntime.converter.impl.parser.support.AbstractFlowStreamParser.parse(AbstractFlowStreamParser.java:53)
	at com.alibaba.compileflow.engine.process.preruntime.converter.impl.TbbpmModelConverter.convertToModel(TbbpmModelConverter.java:38)
	at com.alibaba.compileflow.idea.graph.codec.impl.tbbpm.TbbpmModelCodeConvertExtImpl.buildProcessRuntime(TbbpmModelCodeConvertExtImpl.java:64)
	at com.alibaba.compileflow.idea.graph.codec.impl.tbbpm.TbbpmModelCodeConvertExtImpl.getJavaCode(TbbpmModelCodeConvertExtImpl.java:55)
	at com.alibaba.compileflow.idea.plugin.provider.fileeditor.JavaSourceFileEditor.loadJavaCode(JavaSourceFileEditor.java:131)
	at com.alibaba.compileflow.idea.plugin.provider.fileeditor.JavaSourceFileEditor.lambda$new$0(JavaSourceFileEditor.java:107)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NullPointerException
	at com.alibaba.compileflow.idea.graph.codec.impl.tbbpm.StringFlowStreamSource.getFlow(StringFlowStreamSource.java:39)
	at com.alibaba.compileflow.idea.graph.codec.impl.tbbpm.StringFlowStreamSource.getFlow(StringFlowStreamSource.java:29)
	at com.alibaba.compileflow.engine.process.preruntime.converter.impl.parser.support.AbstractFlowStreamParser.parse(AbstractFlowStreamParser.java:62)
	... 33 more

**Comment by sunhuo** [comment]
idea中报错

**Comment by blake8816** [comment]
2021.1版本的idea，编辑器调整的内容并不生效，也就是text里面根本没有改动，text里面调整了编辑器也没有同步

**Comment by NameCharles** [comment]
阿里全家桶，持续进货中

**Comment by kakaxiTeacher** [comment]
直接解散了钉钉群？  一堆Bug也不解决，问题也不回答，直接关闭得了吧，浪费时间

**Comment by voff12** [comment]
> ```
> 直接解散了钉钉群？  一堆Bug也不解决，问题也不回答，直接关闭得了吧，浪费时间
> ```

都在努力解决中，谢谢你的建议

**Comment by zhanglijie123** [comment]
这个问题反馈好慢啊

**Comment by xuan698400** [comment]
> 这个问题反馈好慢啊

啥问题，可以提交一个iusses，贴的连接，我看到了会持续修复的。上面的报错？

**Comment by boengood** [comment]
使用插件时候，开新idea窗口打开非flow项目报以下错误

com.alibaba.compileflow.engine.common.CompileFlowException: [com.alibaba.compileflow.engine.process.preruntime.validator.ValidateMessage@1b9be6b8]
	at com.alibaba.compileflow.engine.runtime.impl.AbstractProcessRuntime.validateRuntime(AbstractProcessRuntime.java:566)
	at com.alibaba.compileflow.engine.runtime.impl.AbstractProcessRuntime.init(AbstractProcessRuntime.java:202)
	at com.alibaba.compileflow.engine.runtime.impl.TbbpmProcessRuntime.init(TbbpmProcessRuntime.java:92)
	at com.alibaba.compileflow.idea.graph.codec.impl.tbbpm.TbbpmModelCodeConvertExtImpl.buildProcessRuntime(TbbpmModelCodeConvertExtImpl.java:67)
	at com.alibaba.compileflow.idea.graph.codec.impl.tbbpm.TbbpmModelCodeConvertExtImpl.getJavaCode(TbbpmModelCodeConvertExtImpl.java:52)
	at com.alibaba.compileflow.idea.plugin.provider.fileeditor.JavaSourceFileEditor.loadJavaCode(JavaSourceFileEditor.java:96)
	at com.alibaba.compileflow.idea.plugin.provider.fileeditor.JavaSourceFileEditor.access$000(JavaSourceFileEditor.java:58)
	at com.alibaba.compileflow.idea.plugin.provider.fileeditor.JavaSourceFileEditor$1.lambda$selectionChanged$0(JavaSourceFileEditor.java:80)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:350)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:887)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:488)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by chinadeer** [comment]
有钉钉群么?

**Comment by cheerflora** [comment]
![image](https://user-images.githubusercontent.com/45070727/172984153-79eacab3-0180-4df8-be89-fb48a8bb4f44.png)
方法的出参跟入参为啥没地方添加 要怎么添加啊

**Comment by xuan698400** [comment]
> ![image](https://user-images.githubusercontent.com/45070727/172984153-79eacab3-0180-4df8-be89-fb48a8bb4f44.png) 方法的出参跟入参为啥没地方添加 要怎么添加啊

这个是自动识别的，会根据你选择的方法取到方法的出入参的，你这里没有，你检查下，是不是你的cal方法没有出入参

**Comment by cheerflora** [comment]
我的方法有出入参

**Comment by cheerflora** [comment]
可以了 要通过那个browse选择后 双击下就出来了

**Comment by cheerflora** [comment]
这个引擎是不是只能让流程从开始直接跑到结束，没有办法一个环节一个环节去触发？

**Comment by lindadadada1** [comment]
使用

**Comment by SuperRookieMam** [comment]
可视化编辑后如何去查看变动后的 xml  bpm文件，一直未找到保存或预览可视化为xml 的地方

**Comment by KunBoy5240** [comment]
如果是在resource下面新建了一个文件夹在里面放入bpm文件，那么怎么指定他的位置？

**Comment by KunBoy5240** [comment]
打开ide报错
com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.PsiPlainTextFileImpl #TEXT  because: file://D:/project/compileflow-demo/src/main/resources/bpm/ktv/ktvExample.bpm (invalid) is invalid
invalidated at: see attachment
	at com.intellij.psi.impl.source.PsiFileImpl.getText(PsiFileImpl.java:306)
	at com.alibaba.compileflow.idea.plugin.provider.fileeditor.JavaSourceFileEditor.loadJavaCode(JavaSourceFileEditor.java:90)
	at com.alibaba.compileflow.idea.plugin.provider.fileeditor.JavaSourceFileEditor.access$000(JavaSourceFileEditor.java:58)
	at com.alibaba.compileflow.idea.plugin.provider.fileeditor.JavaSourceFileEditor$1.lambda$selectionChanged$0(JavaSourceFileEditor.java:80)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by qiaolin-li** [comment]
插件用不了，报错
这个花流程图的能单独开源出来吗？支持JSON的方式建立流程图的关系

**Comment by Arisaematis** [comment]
除了钉钉的群，还有没有别的群

**Comment by zhouyou9505** [comment]
好像维护这个开源框架的这帮哥们都离职了 想维护也费劲
